import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models
from PIL import Image
import csv
import os

# ---------- CONFIG ----------
CSV_FILE = 'pseudo_severity.csv'        # Generated by severity_prep.py
CKPT_PATH = 'models/best_classifier.pth' # Your existing classifier
SAVE_PATH = 'models/severity_model.pth'
BATCH_SIZE = 16
LR = 1e-4
EPOCHS = 10
# ----------------------------

class PotatoSeverityModel(nn.Module):
    def __init__(self, num_classes=3):
        super().__init__()
        # Base ResNet backbone
        self.backbone = models.resnet34(pretrained=True)
        in_features = self.backbone.fc.in_features
        
        # Remove original fc to use backbone as feature extractor
        self.backbone.fc = nn.Identity()
        
        # 1. Classification Head (preserve existing task)
        self.fc_class = nn.Linear(in_features, num_classes)
        
        # 2. Severity Regression Head (new task)
        # Simple MLP: Features -> 64 -> 1 (Sigmoid for 0-100%)
        self.fc_severity = nn.Sequential(
            nn.Linear(in_features, 64),
            nn.ReLU(),
            nn.Linear(64, 1),
            nn.Sigmoid() 
        )

    def forward(self, x):
        # Get features (B, 512)
        x = self.backbone(x)
        
        # Heads
        cls_logits = self.fc_class(x)
        sev_pred = self.fc_severity(x)
        return cls_logits, sev_pred

class SeverityDataset(Dataset):
    def __init__(self, csv_file, transform=None):
        self.data = []
        with open(csv_file, 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                self.data.append(row)
        self.transform = transform

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        item = self.data[idx]
        img_path = item['path']
        
        # Load image
        try:
            image = Image.open(img_path).convert('RGB')
        except Exception:
            # Fallback for broken paths if necessary
            image = Image.new('RGB', (224, 224))
            
        if self.transform:
            image = self.transform(image)
            
        label = int(item['class'])
        severity = float(item['severity'])
        
        return image, label, torch.tensor(severity, dtype=torch.float32)

def train():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Training on {device}")

    # 1. Setup Data
    tf = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])
    
    if not os.path.exists(CSV_FILE):
        print(f"Error: {CSV_FILE} not found. Run severity_prep.py first.")
        return

    dataset = SeverityDataset(CSV_FILE, transform=tf)
    loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)

    # 2. Setup Model
    model = PotatoSeverityModel(num_classes=3).to(device)
    
    # Load previous classifier weights if available
    if os.path.exists(CKPT_PATH):
        print(f"Loading backbone from {CKPT_PATH}...")
        ckpt = torch.load(CKPT_PATH, map_location=device)
        state_dict = ckpt['model_state'] if 'model_state' in ckpt else ckpt
        
        # Remap keys: original 'layer1...' -> 'backbone.layer1...'
        # original 'fc...' -> 'fc_class...'
        new_state = {}
        for k, v in state_dict.items():
            if k.startswith('fc'):
                new_state[k.replace('fc', 'fc_class')] = v
            else:
                new_state[f'backbone.{k}'] = v
        
        # Load compatible keys (strict=False allows missing fc_severity weights)
        model.load_state_dict(new_state, strict=False)
    
    # 3. Optimization
    optimizer = optim.Adam(model.parameters(), lr=LR)
    criterion_cls = nn.CrossEntropyLoss()
    criterion_sev = nn.L1Loss() # L1 Loss is robust for regression

    # 4. Training Loop
    model.train()
    for epoch in range(EPOCHS):
        running_loss = 0.0
        for imgs, labels, sevs in loader:
            imgs, labels, sevs = imgs.to(device), labels.to(device), sevs.to(device)
            
            optimizer.zero_grad()
            cls_out, sev_out = model(imgs)
            
            # Calculate losses
            loss_c = criterion_cls(cls_out, labels)
            loss_s = criterion_sev(sev_out.squeeze(), sevs)
            
            # Combine losses (weight severity more to focus learning there)
            loss = loss_c + 10.0 * loss_s 
            
            loss.backward()
            optimizer.step()
            running_loss += loss.item()
            
        print(f"Epoch {epoch+1}/{EPOCHS} | Loss: {running_loss/len(loader):.4f}")

    # Save
    torch.save(model.state_dict(), SAVE_PATH)
    print(f"Model saved to {SAVE_PATH}")

if __name__ == '__main__':
    train()